### ISSUE TITLE
Extra rerenders

### ISSUE THREAD

**Issue by lishine** [fabiospampinato/store#3]
Why is that:
> It's possible that the component will be re-rendered even if the object returned by the selector, or the entire store, didn't actually change.

How the selector helps with performance (I mean if I just access store.a.b.c, not some computation) ?
Can I purely use the
store = useStore(store) 
store.a.b
and the component will rerender only when store.a.b changes?
Does it work like react-mobx, just with easier interface - useStore ?

**Comment by fabiospampinato** [comment]
> Why is that:

You can for example flip a boolean twice in a single tick and then fetch it from a selector, it's more expensive to deeply compare the returned values from the selector than just consider that a change and rerender.

> How the selector helps with performance (I mean if I just access store.a.b.c, not some computation) ?

If you only access `a.c`, and only `b` changes, then the library is able to infer that nothing that you need changed, so it skips a rendering.

> Can I purely use the
> store = useStore(store)
> store.a.b
> and the component will rerender only when store.a.b changes?

No, this will make your components rerender whenever anything in `store` changes.

> Does it work like react-mobx, just with easier interface - useStore ?

I don't know.
