### ISSUE TITLE
Why to use this store instead of Redux

### ISSUE THREAD

**Issue by Svetloslav15** [fabiospampinato/store#4]
What are the advantages?

**Comment by fabiospampinato** [comment]
I'm not a redux expert, if you are the best option here is just trying out Store and see the differences for yourself.

Broadly I would say from my point of view compared to redux this is just a much cleaner way to manage state, and you can't mess-up immutable updates, and you don't need stuff like trunks, sagas or whatever.

**Comment by Svetloslav15** [comment]
Ok cool, I just wanted to understand the pros of it and I will try it. Thanks
